// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbsothhwfhpkpujlnkmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRic290aGh3Zmhwa3B1amxua21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTIxNjAsImV4cCI6MjA1ODc2ODE2MH0.eqS8Kn3z9ZWgo1T4jg2MOF_MxUf7KZvxDGwaUMAhd0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);